In [2]:
import numpy as np

In [4]:
# 1
np.arange(10, 90, 10).reshape(-1, 4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
# 2
m = np.arange(0, 15).reshape(-1, 5)
m[1, 2], m[2, 4], m[1, 1:3], m[1:, 2], m[:2,3:5]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

In [15]:
# 3
f = m.flatten()
[i for i in range(len(f)) if i % 3 == 0], [i for i in range(len(f)) if i % 4 == 1], [i for i in range(len(f)) if i % 3 == 0 and i % 4 == 1]

([0, 3, 6, 9, 12], [1, 5, 9, 13], [9])

In [18]:
# 4
np.eye(5, 5) * 2 + np.eye(5, 5, -1) * 3 + np.eye(5, 5, 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [23]:
# 5
m = np.random.uniform(0,10, 30).reshape(5, 6)
m.max(), m.sum(axis = 1), m.max(axis = 1), m.mean(axis = 0), m.min(axis = 0)

(9.555227113882172,
 array([28.68344748, 19.56573653, 38.87121906, 23.69727986, 22.57360459]),
 array([6.99424702, 5.07239822, 9.42228742, 9.52379474, 9.55522711]),
 array([3.96751351, 4.2398834 , 4.82440638, 4.92058111, 5.68810388,
        3.03776922]),
 array([0.44946685, 1.17730157, 0.95968739, 1.3010046 , 1.08044703,
        1.28424109]))

In [44]:
# 6
test = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
test[:, test[1].argsort()]  # test[전체, 열을 1행기준으로 정렬]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [13]:
# 7
np.random.uniform(1, 7, 100).mean()

3.9714063519638345

In [18]:
# 8
stock = [10000]
for _ in range(0, 250) :
    stock.append(np.random.normal(0, 1) * 0.01 * stock[-1] + stock[-1]) # random.normal(기댓값/모평균, 표준편차, 갯수)
np.around(stock)

array([10000., 10112., 10076.,  9907.,  9851.,  9794.,  9560.,  9698.,
        9547.,  9752.,  9624.,  9532.,  9736.,  9702.,  9565.,  9571.,
        9435.,  9358.,  9488.,  9384.,  9493.,  9472.,  9531.,  9558.,
        9580.,  9637.,  9483.,  9630.,  9506.,  9483.,  9522.,  9591.,
        9374.,  9488.,  9581.,  9715.,  9855., 10014., 10095., 10136.,
       10294., 10346., 10294., 10371., 10266., 10024., 10060., 10017.,
        9975.,  9872.,  9840.,  9916.,  9951.,  9855., 10033.,  9985.,
        9800.,  9637.,  9524.,  9554.,  9652.,  9579.,  9678.,  9644.,
        9589.,  9475.,  9478.,  9584.,  9588.,  9555.,  9709.,  9806.,
        9930.,  9993.,  9940., 10087., 10016.,  9890.,  9666.,  9652.,
        9629.,  9710.,  9739.,  9673.,  9710.,  9712.,  9777.,  9765.,
        9737.,  9756.,  9784.,  9769.,  9826.,  9796.,  9870., 10007.,
        9917.,  9946.,  9868., 10015., 10131., 10051., 10030.,  9936.,
        9981.,  9841.,  9851.,  9949.,  9856.,  9780.,  9804.,  9888.,
      