In [2]:
import numpy as np

In [4]:
# 1
np.arange(10, 90, 10).reshape(-1, 4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
# 2
m = np.arange(0, 15).reshape(-1, 5)
m[1, 2], m[2, 4], m[1, 1:3], m[1:, 2], m[:2,3:5]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

In [15]:
# 3
f = m.flatten()
[i for i in range(len(f)) if i % 3 == 0], [i for i in range(len(f)) if i % 4 == 1], [i for i in range(len(f)) if i % 3 == 0 and i % 4 == 1]

([0, 3, 6, 9, 12], [1, 5, 9, 13], [9])

In [18]:
# 4
np.eye(5, 5) * 2 + np.eye(5, 5, -1) * 3 + np.eye(5, 5, 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [23]:
# 5
m = np.random.uniform(0,10, 30).reshape(5, 6)
m.max(), m.sum(axis = 1), m.max(axis = 1), m.mean(axis = 0), m.min(axis = 0)

(9.555227113882172,
 array([28.68344748, 19.56573653, 38.87121906, 23.69727986, 22.57360459]),
 array([6.99424702, 5.07239822, 9.42228742, 9.52379474, 9.55522711]),
 array([3.96751351, 4.2398834 , 4.82440638, 4.92058111, 5.68810388,
        3.03776922]),
 array([0.44946685, 1.17730157, 0.95968739, 1.3010046 , 1.08044703,
        1.28424109]))

In [44]:
# 6
test = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
test[:, test[1].argsort()]  # test[전체, 열을 1행기준으로 정렬]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [6]:
# 7
np.random.uniform(1, 6, 100).mean()

3.6596662188213878

In [14]:
# 8
np.random.seed(10000)
np.random.normal(0, 1, 250) # random.normal(기댓값/모평균, 표준편차, 갯수)

array([-1.27109064,  0.17613707, -0.29621638,  0.32692882, -0.97341942,
        0.227681  , -0.81932804,  0.10722255,  0.97527763,  0.08197388,
       -0.47662253, -1.49217154, -0.40346495,  0.69477827,  0.2121528 ,
        0.09098984, -1.54885465, -0.04482736,  1.55676333,  1.94711068,
       -0.78514011, -2.13921194, -1.26425853,  0.29498718,  0.80648927,
        0.27767032, -1.24384504,  0.78727437,  0.75203041,  0.17298001,
       -0.73783565,  0.96919093, -0.64637056,  1.81109463, -0.99044486,
       -1.36911291,  0.07248481,  0.40832729,  0.1687738 , -0.58670124,
       -1.51733757,  0.72040884, -2.14986374, -1.23310196, -0.12122475,
        0.68214936,  1.26832604, -0.02907836, -0.80203131,  0.67907827,
       -1.04111161,  0.93386042,  0.34352489,  1.78771666,  0.48640788,
        0.46039938, -0.83387849,  0.04040953, -0.09290729, -0.75064297,
       -0.37392144,  0.3453563 ,  0.49987149, -1.1674225 , -0.38700182,
       -0.96593647, -2.36935061,  1.11943353,  1.14754071,  1.19