In [2]:
import numpy as np

In [4]:
# 1
np.arange(10, 90, 10).reshape(-1, 4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
# 2
m = np.arange(0, 15).reshape(-1, 5)
m[1, 2], m[2, 4], m[1, 1:3], m[1:, 2], m[:2,3:5]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

In [15]:
# 3
f = m.flatten()
[i for i in range(len(f)) if i % 3 == 0], [i for i in range(len(f)) if i % 4 == 1], [i for i in range(len(f)) if i % 3 == 0 and i % 4 == 1]

([0, 3, 6, 9, 12], [1, 5, 9, 13], [9])

In [18]:
# 4
np.eye(5, 5) * 2 + np.eye(5, 5, -1) * 3 + np.eye(5, 5, 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [23]:
# 5
m = np.random.uniform(0,10, 30).reshape(5, 6)
m.max(), m.sum(axis = 1), m.max(axis = 1), m.mean(axis = 0), m.min(axis = 0)

(9.555227113882172,
 array([28.68344748, 19.56573653, 38.87121906, 23.69727986, 22.57360459]),
 array([6.99424702, 5.07239822, 9.42228742, 9.52379474, 9.55522711]),
 array([3.96751351, 4.2398834 , 4.82440638, 4.92058111, 5.68810388,
        3.03776922]),
 array([0.44946685, 1.17730157, 0.95968739, 1.3010046 , 1.08044703,
        1.28424109]))

In [44]:
# 6
test = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
test[:, test[1].argsort()]  # test[전체, 열을 1행기준으로 정렬]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [6]:
# 7
np.random.uniform(1, 6, 100).mean()

3.6596662188213878

In [197]:
# 8
stock = [10000]
for _ in range(0, 250) :
    stock.append(np.random.normal(0, 1) * 0.01 * stock[-1] + stock[-1]) # random.normal(기댓값/모평균, 표준편차, 갯수)
np.around(stock)

array([10000.,  9995.,  9761.,  9899.,  9804.,  9796.,  9785.,  9813.,
        9873.,  9971.,  9969., 10084., 10091.,  9888.,  9917., 10017.,
       10174., 10393., 10464., 10386., 10230., 10256., 10122.,  9958.,
        9904.,  9828.,  9723.,  9679.,  9543.,  9508.,  9476.,  9417.,
        9515.,  9595.,  9700.,  9752.,  9795.,  9766.,  9885.,  9968.,
       10190., 10216., 10103., 10148., 10214., 10199., 10154., 10111.,
       10154., 10174., 10057., 10077., 10083., 10027.,  9899.,  9883.,
        9813.,  9898.,  9926.,  9928.,  9870.,  9692.,  9792.,  9771.,
        9784.,  9673.,  9727.,  9923.,  9886.,  9873., 10023.,  9939.,
       10060., 10015., 10053.,  9968.,  9915.,  9867.,  9803.,  9763.,
        9722.,  9803.,  9707.,  9689.,  9766.,  9600.,  9550.,  9633.,
        9521.,  9619.,  9619.,  9547.,  9418.,  9402.,  9369.,  9429.,
        9472.,  9478.,  9473.,  9615.,  9811.,  9776.,  9913.,  9782.,
        9751.,  9849.,  9909.,  9998.,  9951.,  9752.,  9765.,  9779.,
      